### ISSUE TITLE
Why does Lyra not allow inline styles? Should we allow them or not?

### ISSUE THREAD

**Issue by Nathan-Patnam** [heroku/github-issues-squad#89]

**Comment by Nathan-Patnam** [comment]
Jamie White:

Be aware that the reason linter doesn’t like inline styles is because they can be a vector for cross-site-scripting exploits. (I know, this is why we can’t have nice things)

This was his response to asking him if all I need to use is  'htmlSafe'

confusingly, `htmlSafe` doesn’t actually perform any sanitization, it just marks the string as “safe” as in “this string is safe to insert directly into the DOM”.

The system is pretty similar to Rails and React — Ember automatically sanitizes every dynamic `{{expression}}` before putting stuff in the DOM so that no nefarious `<script>` tags get injected by untrusted data. Basically every `{{expression}}` is _untrusted_ unless you explicitly say you trust it either with `htmlSafe` or triple-curlies: `{{{data}}}`.

Here was the before:
![](https://files.slack.com/files-pri/T092Z56AE-FKQ791QMB/image.png)

Here was Jamie's suggested code change:
```
<p class="flex-auto hk-badge--square mh1" style="background-color: {{sanitizedBackgroundColor}};">

sanitizedBackgroundColor: computed('label.color', function() {
  const color = this.label.color || '';
  const [hex] = this.label.color.match(/[0-9a-fA-F]{6}/) || ['000000'];
  return `#${hex}`;
})

```

https://heroku.slack.com/archives/C1QNM9UJ2/p1560963442067800

**Comment by mimen** [comment]
@jgwhite do you think it's necessary that we refrain from using inline styles for this project? it's an internal tool, and we want to develop it rapidly so I worry this will slow us down a lot.

**Comment by jgwhite** [comment]
> @jgwhite do you think it's necessary that we refrain from using inline styles for this project? it's an internal tool, and we want to develop it rapidly so I worry this will slow us down a lot.

I totally get your argument for avoiding things that might bog down your progress, but also think this is proving a terrific opportunity to discuss both security best practices and the alternatives to inline styles. Not only that, but it’s also a fabulous opportunity to discuss a powerful new feature of Ember that we can adopt right away: [element modifiers](https://blog.emberjs.com/2019/03/06/coming-soon-in-ember-octane-part-4.html).

Element modifiers are pretty new but the Ember community is super excited about the possibilities and, as a result, somebody has already created exactly the modifier we need for this situation: [ember-style-modifier](https://emberobserver.com/addons/ember-style-modifier). This lovely modifier means we can skip my ugly code above and do something like this instead:

```hbs
<p
  class="flex-auto hk-badge--square mh1"
  {{style background-color=this.label.color}}
>
```

This is both concise *and* safe because `style.backgroundColor` won’t interpret any arbitrary CSS, just the allowed subset for specifying background colors. Personally, this is what I’d like to see us move to across the board for cases like this. Y’all are on the vanguard.
